$baseUrl = "https://loremflickr.com/300/300"
$scriptPath = $MyInvocation.MyCommand.Path
$scriptDir = Split-Path $scriptPath
$targetDir = Join-Path $scriptDir "..\src\assets\products"
$targetDir = [System.IO.Path]::GetFullPath($targetDir)

Write-Host "Target Directory: $targetDir"

if (!(Test-Path $targetDir)) {
    New-Item -ItemType Directory -Force -Path $targetDir
}

$products = @(
    @{ Name = "banana"; Keyword = "banana" },
    @{ Name = "tomato"; Keyword = "tomato" },
    @{ Name = "potato"; Keyword = "potato" },
    @{ Name = "onion"; Keyword = "onion" },
    @{ Name = "garlic"; Keyword = "garlic" },
    @{ Name = "lemon"; Keyword = "lemon" },
    @{ Name = "lime"; Keyword = "lime" },
    @{ Name = "orange"; Keyword = "orange" },
    @{ Name = "lettuce"; Keyword = "lettuce" },
    @{ Name = "spinach"; Keyword = "spinach" },
    @{ Name = "cucumber"; Keyword = "cucumber" },
    @{ Name = "broccoli"; Keyword = "broccoli" },
    @{ Name = "bell_pepper"; Keyword = "bell pepper" },
    @{ Name = "avocado"; Keyword = "avocado" },
    @{ Name = "grapes"; Keyword = "grapes" },
    @{ Name = "strawberry"; Keyword = "strawberry" },
    @{ Name = "blueberry"; Keyword = "blueberry" },
    @{ Name = "watermelon"; Keyword = "watermelon" },
    @{ Name = "zucchini"; Keyword = "zucchini" },
    @{ Name = "mushroom"; Keyword = "mushroom" },
    @{ Name = "corn"; Keyword = "corn" },
    @{ Name = "ginger"; Keyword = "ginger" },
    @{ Name = "eggs"; Keyword = "eggs" },
    @{ Name = "butter"; Keyword = "butter" },
    @{ Name = "yogurt"; Keyword = "yogurt" },
    @{ Name = "cream_cheese"; Keyword = "cream cheese" },
    @{ Name = "sour_cream"; Keyword = "sour cream" },
    @{ Name = "heavy_cream"; Keyword = "milk cream" },
    @{ Name = "orange_juice"; Keyword = "orange juice" },
    @{ Name = "tofu"; Keyword = "tofu" },
    @{ Name = "rice"; Keyword = "rice grain" },
    @{ Name = "pasta"; Keyword = "pasta" },
    @{ Name = "flour"; Keyword = "flour" },
    @{ Name = "sugar"; Keyword = "sugar" },
    @{ Name = "oats"; Keyword = "oats" },
    @{ Name = "bagels"; Keyword = "bagel" },
    @{ Name = "tortillas"; Keyword = "tortilla" },
    @{ Name = "quinoa"; Keyword = "quinoa" },
    @{ Name = "ground_beef"; Keyword = "ground beef" },
    @{ Name = "pork"; Keyword = "pork meat" },
    @{ Name = "bacon"; Keyword = "bacon" },
    @{ Name = "sausage"; Keyword = "sausage" },
    @{ Name = "ham"; Keyword = "ham meat" },
    @{ Name = "turkey"; Keyword = "roasted turkey" },
    @{ Name = "fish"; Keyword = "fish fillet" },
    @{ Name = "salmon"; Keyword = "salmon fillet" },
    @{ Name = "shrimp"; Keyword = "shrimp" },
    @{ Name = "canned_beans"; Keyword = "beans" },
    @{ Name = "lentils"; Keyword = "lentils" },
    @{ Name = "olive_oil"; Keyword = "olive oil" },
    @{ Name = "veg_oil"; Keyword = "oil bottle" },
    @{ Name = "salt"; Keyword = "salt shaker" },
    @{ Name = "pepper"; Keyword = "black pepper" },
    @{ Name = "spices"; Keyword = "spices" },
    @{ Name = "tomato_sauce"; Keyword = "tomato sauce" },
    @{ Name = "peanut_butter"; Keyword = "peanut butter" },
    @{ Name = "jam"; Keyword = "fruit jam" },
    @{ Name = "honey"; Keyword = "honey jar" },
    @{ Name = "mayo"; Keyword = "mayonnaise" },
    @{ Name = "ketchup"; Keyword = "ketchup" },
    @{ Name = "mustard"; Keyword = "mustard condiment" },
    @{ Name = "soy_sauce"; Keyword = "soy sauce" },
    @{ Name = "vinegar"; Keyword = "vinegar bottle" },
    @{ Name = "soup"; Keyword = "soup bowl" },
    @{ Name = "cereal"; Keyword = "cereal bowl" },
    @{ Name = "chips"; Keyword = "potato chips" },
    @{ Name = "crackers"; Keyword = "crackers" },
    @{ Name = "nuts"; Keyword = "mixed nuts" },
    @{ Name = "coffee"; Keyword = "coffee cup" },
    @{ Name = "tea"; Keyword = "tea cup" },
    @{ Name = "soda"; Keyword = "soda can" },
    @{ Name = "water"; Keyword = "water bottle" },
    @{ Name = "beer"; Keyword = "beer glass" },
    @{ Name = "wine"; Keyword = "wine bottle" },
    @{ Name = "dish_soap"; Keyword = "dish soap" },
    @{ Name = "trash_bags"; Keyword = "trash bag" },
    @{ Name = "paper_towels"; Keyword = "paper towel roll" },
    @{ Name = "tp"; Keyword = "toilet paper" },
    @{ Name = "laundry_det"; Keyword = "laundry detergent" },
    @{ Name = "dishwasher_pods"; Keyword = "dishwasher" },
    @{ Name = "batteries"; Keyword = "batteries" },
    @{ Name = "light_bulbs"; Keyword = "light bulb" },
    @{ Name = "shampoo"; Keyword = "shampoo bottle" },
    @{ Name = "conditioner"; Keyword = "conditioner bottle" },
    @{ Name = "body_wash"; Keyword = "body wash" },
    @{ Name = "soap_bar"; Keyword = "soap bar" },
    @{ Name = "toothpaste"; Keyword = "toothpaste" },
    @{ Name = "toothbrush"; Keyword = "toothbrush" },
    @{ Name = "deodorant"; Keyword = "deodorant stick" },
    @{ Name = "razor"; Keyword = "razor shaving" },
    @{ Name = "lotion"; Keyword = "lotion bottle" },
    @{ Name = "sunscreen"; Keyword = "sunscreen" },
    @{ Name = "ice_cream"; Keyword = "ice cream" },
    @{ Name = "frozen_pizza"; Keyword = "frozen pizza" },
    @{ Name = "frozen_veggies"; Keyword = "frozen vegetables" },
    @{ Name = "fries"; Keyword = "french fries" },
    @{ Name = "nuggets"; Keyword = "chicken nuggets" },
    @{ Name = "diapers"; Keyword = "baby diapers" },
    @{ Name = "wipes"; Keyword = "wet wipes" },
    @{ Name = "baby_food"; Keyword = "baby food string" },
    @{ Name = "formula"; Keyword = "baby milk formula" },
    @{ Name = "dog_food"; Keyword = "dog food bag" },
    @{ Name = "cat_food"; Keyword = "cat food" },
    @{ Name = "cat_litter"; Keyword = "cat litter" },
    @{ Name = "dog_treats"; Keyword = "dog treats" },
    @{ Name = "pain_reliever"; Keyword = "pills bottle" },
    @{ Name = "bandages"; Keyword = "bandaid" },
    @{ Name = "vitamins"; Keyword = "medication vitamins" },
    @{ Name = "cough_syrup"; Keyword = "cough syrup" },
    @{ Name = "ramen"; Keyword = "ramen bowl" },
    @{ Name = "curry_paste"; Keyword = "curry paste" },
    @{ Name = "salsa"; Keyword = "salsa jar" },
    @{ Name = "baking_powder"; Keyword = "baking powder" },
    @{ Name = "vanilla"; Keyword = "vanilla extract" },
    @{ Name = "choc_chips"; Keyword = "chocolate chips" },
    @{ Name = "pens"; Keyword = "pens school" },
    @{ Name = "notebook"; Keyword = "notebook" },
    @{ Name = "printer_paper"; Keyword = "printer paper" },
    @{ Name = "tape"; Keyword = "scotch tape" },
    @{ Name = "scissors"; Keyword = "scissors" },
    @{ Name = "envelopes"; Keyword = "envelopes" },
    @{ Name = "balloons"; Keyword = "balloons" },
    @{ Name = "candles"; Keyword = "birthday candles" },
    @{ Name = "paper_plates"; Keyword = "paper plates" },
    @{ Name = "red_cups"; Keyword = "red plastic cups" },
    @{ Name = "napkins"; Keyword = "table napkins" },
    @{ Name = "soil"; Keyword = "potting soil" },
    @{ Name = "seeds"; Keyword = "plant seeds packet" },
    @{ Name = "fertilizer"; Keyword = "plant fertilizer" },
    @{ Name = "garden_hose"; Keyword = "garden hose" },
    @{ Name = "shovel"; Keyword = "garden trowel" },
    @{ Name = "popcorn"; Keyword = "popcorn" },
    @{ Name = "pretzels"; Keyword = "pretzels" },
    @{ Name = "gum"; Keyword = "chewing gum" },
    @{ Name = "chocolate"; Keyword = "chocolate bar" },
    @{ Name = "gummies"; Keyword = "gummy bears" },
    @{ Name = "granola_bar"; Keyword = "granola bar" },
    @{ Name = "charger"; Keyword = "phone charger" },
    @{ Name = "usb_cable"; Keyword = "usb cable" },
    @{ Name = "hdmi"; Keyword = "hdmi cable" },
    @{ Name = "aa_batteries"; Keyword = "AA batteries" },
    @{ Name = "aaa_batteries"; Keyword = "AAA batteries" },
    @{ Name = "extension_cord"; Keyword = "extension cord" },
    @{ Name = "hammer"; Keyword = "hammer tool" },
    @{ Name = "screwdriver"; Keyword = "screwdriver" },
    @{ Name = "nails"; Keyword = "metal nails" },
    @{ Name = "screws"; Keyword = "metal screws" },
    @{ Name = "tape_measure"; Keyword = "tape measure" },
    @{ Name = "wrench"; Keyword = "wrench tool" },
    @{ Name = "yoga_mat"; Keyword = "yoga mat" },
    @{ Name = "dumbbells"; Keyword = "dumbbells" },
    @{ Name = "reusable_bottle"; Keyword = "water bottle" },
    @{ Name = "soccer_ball"; Keyword = "soccer ball" },
    @{ Name = "tennis_balls"; Keyword = "tennis ball" },
    @{ Name = "glue_stick"; Keyword = "glue stick" },
    @{ Name = "markers"; Keyword = "colored markers" },
    @{ Name = "yarn"; Keyword = "yarn ball" },
    @{ Name = "paint"; Keyword = "acrylic paint" },
    @{ Name = "brushes"; Keyword = "paint brushes" },
    @{ Name = "pillow"; Keyword = "throw pillow" },
    @{ Name = "blanket"; Keyword = "blanket bed" },
    @{ Name = "scented_candle"; Keyword = "scented candle" },
    @{ Name = "vase"; Keyword = "flower vase" },
    @{ Name = "frame"; Keyword = "picture frame" },
    @{ Name = "tshirt"; Keyword = "plain t-shirt" },
    @{ Name = "socks"; Keyword = "socks" },
    @{ Name = "underwear"; Keyword = "underwear" },
    @{ Name = "hat"; Keyword = "baseball cap" },
    @{ Name = "scarf"; Keyword = "winter scarf" },
    @{ Name = "motor_oil"; Keyword = "motor oil bottle" },
    @{ Name = "wiper_fluid"; Keyword = "windshield washer fluid" },
    @{ Name = "car_wash"; Keyword = "car wash soap" },
    @{ Name = "car_fresh"; Keyword = "car air freshener" },
    @{ Name = "tent"; Keyword = "camping tent" },
    @{ Name = "sleeping_bag"; Keyword = "sleeping bag" },
    @{ Name = "lantern"; Keyword = "camping lantern" },
    @{ Name = "bug_spray"; Keyword = "insect repellent spray" },
    @{ Name = "cooler"; Keyword = "picnic cooler" },
    @{ Name = "novel"; Keyword = "novel book" },
    @{ Name = "cookbook"; Keyword = "cookbook" },
    @{ Name = "board_game"; Keyword = "board game box" },
    @{ Name = "puzzle"; Keyword = "jigsaw puzzle" },
    @{ Name = "cards"; Keyword = "playing cards" },
    @{ Name = "suitcase"; Keyword = "suitcase" },
    @{ Name = "backpack"; Keyword = "backpack" },
    @{ Name = "travel_pillow"; Keyword = "neck pillow" },
    @{ Name = "eye_mask"; Keyword = "sleep mask" },
    @{ Name = "necklace"; Keyword = "gold necklace" },
    @{ Name = "ring"; Keyword = "gold ring" },
    @{ Name = "earrings"; Keyword = "earrings jewelry" },
    @{ Name = "watch"; Keyword = "wristwatch" },
    @{ Name = "chair"; Keyword = "living room chair" },
    @{ Name = "desk"; Keyword = "office desk" },
    @{ Name = "bookshelf"; Keyword = "wooden bookshelf" },
    @{ Name = "lamp"; Keyword = "table lamp" },
    @{ Name = "guitar"; Keyword = "acoustic guitar" },
    @{ Name = "piano"; Keyword = "piano keyboard" },
    @{ Name = "drum_sticks"; Keyword = "drum sticks" },
    @{ Name = "headphones"; Keyword = "headphones" }
)

foreach ($item in $products) {
    $filename = $item.Name + ".jpg"
    $filepath = Join-Path $targetDir $filename
    $url = "$baseUrl/" + $item.Keyword
    
    # Overwrite check - for now, always download
    Write-Host "Downloading $($item.Name) from $url..."
    try {
        # Use a user agent to avoid being blocked
        Invoke-WebRequest -Uri $url -OutFile $filepath -TimeoutSec 15 -UserAgent "Mozilla/5.0"
    }
    catch {
        Write-Host "Failed to download $($item.Name): $_"
    }
    
    Start-Sleep -Milliseconds 500
}
Write-Host "Done downloading images."
